(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DAL' object has no attribute 'articulos'"
p3
sS'layer'
p4
S'/home/eddgt/public_html/web2py/web2py/applications/blog/controllers/configmenu.py'
p5
sS'code'
p6
S'# coding: utf8\n# intente algo como\ndef index(): return dict(message="hello from configmenu.py")\n\ndef articulos():\n    formulario =SQLFORM.grid(db.articulos)\n    return locals()\n\nresponse._vars=response._caller(articulos)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/eddgt/public_html/web2py/web2py/gluon/restricted.py", line 220, in restricted\n    exec ccode in environment\n  File "/home/eddgt/public_html/web2py/web2py/applications/blog/controllers/configmenu.py", line 9, in <module>\n  File "/home/eddgt/public_html/web2py/web2py/gluon/globals.py", line 385, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/eddgt/public_html/web2py/web2py/applications/blog/controllers/configmenu.py", line 6, in articulos\n    formulario =SQLFORM.grid(db.articulos)\n  File "/home/eddgt/public_html/web2py/web2py/gluon/dal.py", line 8333, in __getattr__\n    return ogetattr(self, key)\nAttributeError: \'DAL\' object has no attribute \'articulos\'\n'
p11
s.